version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: adminpostgres
      POSTGRES_PASSWORD: 87654321
      POSTGRES_DB: shop
    build:
      context: .
      dockerfile: db.Dockerfile
    ports:
      - "5432:5432"
    networks:
      - kafka-network
  
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    networks:
      - kafka-network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR:1
    networks:
      - kafka-network
    command: ["bash", "-c", "KAFKA_AUTO_CREATE_TOPICS_ENABLE=false && /etc/confluent/docker/run"]


  kafka-ui:
    image: landoop/kafka-topics-ui
    environment:
      - KAFKA_REST_PROXY_URL=http://kafka:9092
    ports:
      - "8000:8000"
    networks:
      - kafka-network


  input-harga-service:
    build:
      context: ../microservice/input-harga-service
      dockerfile: Dockerfile
    depends_on:
      - kafka
    networks:
      - kafka-network
    ports:
      - "8080:8080"


  input-harga-storage-service:
    build:
      context: ../microservice/input-harga-storage-service
      dockerfile: Dockerfile
    depends_on:
      - kafka
    networks:
      - kafka-network
    ports:
      - "8081:8080"
      
  topup-service:
    build:
      context: ../microservice/topup-service
      dockerfile: Dockerfile
    depends_on:
      - kafka
    networks:
      - kafka-network
    ports:
      - "8082:8082"

  topup-storage-service:
    build:
      context: ../microservice/topup-storage-service
      dockerfile: Dockerfile
    depends_on:
      - kafka
    networks:
      - kafka-network
    ports:
      - "8083:8080"

  cek-harga-service:
    build:
      context: ../microservice/cek-harga-service
      dockerfile: Dockerfile
    depends_on:
      - kafka
    networks:
      - kafka-network
    ports:
      - "8084:8084"

  cek-mutasi-service:
    build:
      context: ../microservice/cek-mutasi-service
      dockerfile: Dockerfile
    depends_on:
      - kafka
    networks:
      - kafka-network
    ports:
      - "8085:8085"

  cek-saldo-service:
    build:
      context: ../microservice/cek-saldo-service
      dockerfile: Dockerfile
    depends_on:
      - kafka
    networks:
      - kafka-network
    ports:
      - "8086:8086"

  buyback-service:
    build:
      context: ../microservice/buyback-service
      dockerfile: Dockerfile
    depends_on:
      - kafka
    networks:
      - kafka-network
    ports:
      - "8087:8087"

  buyback-storage-service:
    build:
      context: ../microservice/buyback-storage-service
      dockerfile: Dockerfile
    depends_on:
      - kafka
    networks:
      - kafka-network
    ports:
      - "8088:8080"

networks:
  kafka-network:
    driver: bridge
